# Dockerfile
# start from official mongo image
FROM centurylink/mysql
ADD sources1.list /etc/apt/sources1.list
RUN apt-get update && apt-get install -y unzip supervisor
# install consul agent
ADD consul_0.6.4_linux_amd64.zip /tmp/consul.zip
RUN cd /bin && \
    unzip /tmp/consul.zip&& \
    chmod +x /bin/consul && \
    mkdir -p {/data/consul,/etc/consul.d} && \
    rm /tmp/consul.zip
#RUN echo 'nameserver 127.0.0.1' > /etc/resolv.conf
#RUN echo 'nameserver 114.114.114.114' >> /etc/resolv.conf
#RUN echo 'nameserver 8.8.8.8' >> /etc/resolv.conf
# copy service and check definition, as we wrote them earlier
ADD mysql.json /etc/consul.d/mysql.json
ADD 10-consul /etc/dnsmasq.d/10-consul
COPY dnsmasq.conf /etc/dnsmasq.conf

# Install goreman - foreman clone written in Go language

# copy startup script
ADD supervisord.conf /etc/supervisor/conf.d/supervisord.conf
#ADD start.sh /start.sh
EXPOSE 8300 8301 8301/udp 8302 8302/udp 8400 8500 53/udp
# launch both mongo server and consul agent
CMD ["/usr/bin/supervisord"]
